Repository denglihong2007/CRSim, pull requests merged in 2025-06, with the labels that each got.

#170 fix: 改善部分样式显示效果
  CRSim.ScreenSimulator/Views/Ankang/ExitScreenView.xaml
  CRSim.ScreenSimulator/Views/Beijing/ArrivalScreenView.xaml
  CRSim.ScreenSimulator/Views/BeijingNan/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/BeijingNan/TicketCheckScreenView.xaml
  CRSim.ScreenSimulator/Views/BeijingXi/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/ChengduDong/PrimaryTicketCheckScreenView.xaml
  CRSim.ScreenSimulator/Views/ChengduDong/SecondaryScreenView.xaml
  CRSim.ScreenSimulator/Views/DaqingDong/ConcourseBridgeScreenView.xaml
  CRSim.ScreenSimulator/Views/DezhouDong/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/GuangdongIntercity/SecondaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Guangyuan/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Harbin/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Jinanxi/SmallScreenView.xaml
  CRSim.ScreenSimulator/Views/Niuzhou/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Shanghai/OutsideScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/SecondaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/TicketCheckScreenView.xaml
Labels: Bug, 类别：样式

#174 refactor: 更改部分变量、属性、转换器名称 [skip cliff]
  CRSim.ScreenSimulator/Converters/NumberToImageConverter.cs
  CRSim.ScreenSimulator/Converters/TrainStateColorConverter.cs
  CRSim.ScreenSimulator/ViewModels/Ankang/ExitScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/BeijingNan/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/BeijingXi/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/ChengduDong/SecondaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/ChengduShuangliuAirport/SecondaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/DezhouDong/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/GuangdongIntercity/SecondaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Guangyuan/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Harbin/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Jinanxi/SmallScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Niuzhou/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/ScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Shanghai/OutsideScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Zibo/PrimaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Zibo/SecondaryScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Zibo/TicketCheckScreenViewModel.cs
  CRSim.ScreenSimulator/Views/BeijingNan/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/ChengduShuangliuAirport/SecondaryScreenView.xaml
  CRSim.ScreenSimulator/Views/FuzhouNan/TicketCheckScreenView.xaml
  CRSim.ScreenSimulator/Views/GuangdongIntercity/SecondaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Jinanxi/SmallScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/PrimaryScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/SecondaryScreenView.xaml
Labels: 改进, 类别：后端

#177 ci: 优化更新日志输出 [skip cliff]
  .github/workflows/release.yml
  cliff.toml
Labels: Bug, 类别：更新

#184 feat: 添加了淄博站出站口看板
  CRSim.ScreenSimulator/Assets/Zibo/ExitScreen.png
  CRSim.ScreenSimulator/CRSim.ScreenSimulator.csproj
  CRSim.ScreenSimulator/Converters/TrainStateColorConverter.cs
  CRSim.ScreenSimulator/Converters/TrainStateConverter.cs
  CRSim.ScreenSimulator/Models/StylesInfoData.json
  CRSim.ScreenSimulator/ViewModels/ScreenViewModel.cs
  CRSim.ScreenSimulator/ViewModels/Zibo/ExitScreenViewModel.cs
  CRSim.ScreenSimulator/Views/Zibo/ExitScreenView.xaml
  CRSim.ScreenSimulator/Views/Zibo/ExitScreenView.xaml.cs
Labels: 新功能, 类别：样式

#193 fix: 双流机场样式不显示页码
  CRSim.ScreenSimulator/Views/ChengduShuangliuAirport/SecondaryScreenView.xaml
Labels: Bug, 类别：样式
